[package]
name = "z-tab-bar"
version = "0.1.0"
authors = ["Cason Adams <casonadams@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
colored = "*"
ansi_term = "*"
unicode-width = "*"
zellij-tile = "*"
zellij-tile-utils = "*"
